'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const api=require('../scripts/report/genome-braid-clock.js');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/braid_clock/synthetic_explorer.json'),'utf8'));
const copy=x=>JSON.parse(JSON.stringify(x));
const phen=()=>api.validatePhenology(copy(fixture.ecological_clock));
const sample=()=>copy(fixture.samples[2]);

test('eight literal segment keys preserve NA',()=>{
  const m=api.model(copy(fixture));assert.equal(Object.keys(m.bySegment).length,8);
  assert.equal(api.presence(m,'s:DEMO-03','NA').status,'PRESENT');
});
test('model is nonmutating',()=>{const d=copy(fixture),s=JSON.stringify(d);api.model(d);assert.equal(JSON.stringify(d),s);});
test('duplicate sample identities fail',()=>{const d=copy(fixture);d.samples.push(d.samples[0]);assert.throws(()=>api.model(d),/unique/);});
test('missing tree is not missing tip',()=>{const d=copy(fixture);delete d.trees.HA;const m=api.model(d);assert.equal(api.presence(m,'s:DEMO-04','PB2').status,'ABSENT_FROM_TREE');assert.equal(api.presence(m,'s:DEMO-04','HA').status,'NO_TREE');});
test('unannotated tips are not guessed from a name prefix',()=>{const d=copy(fixture);d.trees.HA.root={children:[{name:'DEMO-03__HA',length:.1}]};assert.equal(api.presence(api.model(d),'s:DEMO-03','HA').status,'ABSENT_FROM_TREE');});
test('duplicated tip identity is flagged, not linked arbitrarily',()=>{const d=copy(fixture);d.trees.HA.root={children:[{name:'x',sample_id:'DEMO-03',length:.1},{name:'y',sample_id:'DEMO-03',length:.2}]};const m=api.model(d);assert.equal(api.presence(m,'s:DEMO-03','HA').status,'MULTIPLE_TIPS');assert.equal(m.warnings.length,1);});
test('public references cannot silently enter sample neighborhood metric',()=>{const m=api.model(copy(fixture));assert.equal(api.neighborhoodProfile(m,'r:DEMO-REF-1').status,'SAMPLES_ONLY');});
test('shared-neighbor overlap is invariant to child-order rotation',()=>{const d=copy(fixture);function rotate(n){if(n.children){n.children.reverse();n.children.forEach(rotate);}}for(const t of Object.values(d.trees))rotate(t.root);assert.deepEqual(api.neighborhoodProfile(api.model(d),'s:DEMO-03'),api.neighborhoodProfile(api.model(copy(fixture)),'s:DEMO-03'));});
test('identical trees give full overlap when cutoff is not tied',()=>{const d=copy(fixture);for(const s of api.SEGMENTS)d.trees[s]=copy(d.trees.HA);const p=api.neighborhoodProfile(api.model(d),'s:DEMO-03');assert.equal(p.mean,1);assert.equal(p.available,28);});
test('tied nearest-neighbor cutoff is not broken by ID',()=>{const d=copy(fixture);for(const s of api.SEGMENTS)d.trees[s]={root:{children:d.samples.map(e=>({name:e.sample_id,sample_id:e.sample_id,length:.1}))}};const p=api.neighborhoodProfile(api.model(d),'s:DEMO-03');assert.equal(p.mean,null);assert.equal(p.available,0);assert.ok(p.pairs.every(x=>x.status==='TIED_CUTOFF'));});
test('missing branch lengths are not interpreted as zero distance',()=>{const d=copy(fixture);for(const s of api.SEGMENTS)d.trees[s]={root:{children:d.samples.map(e=>({name:e.sample_id,sample_id:e.sample_id}))}};const p=api.neighborhoodProfile(api.model(d),'s:DEMO-03');assert.equal(p.mean,null);assert.ok(p.pairs.every(x=>x.status==='INVALID_LENGTHS'));});
test('negative branch lengths invalidate comparison',()=>{const d=copy(fixture);for(const s of api.SEGMENTS)d.trees[s]={root:{children:d.samples.map((e,i)=>({name:e.sample_id,sample_id:e.sample_id,length:i===2?-.1:.1+i*.01}))}};assert.equal(api.neighborhoodProfile(api.model(d),'s:DEMO-03').mean,null);});
test('too few shared identities do not become perfect overlap',()=>{const d=copy(fixture);d.samples=d.samples.slice(0,3);const p=api.neighborhoodProfile(api.model(d),'s:DEMO-03');assert.equal(p.available,0);});
test('ISO date validation rejects rolled-over impossible dates',()=>{assert.equal(api.strictDate('2025-02-29'),null);assert.equal(api.strictDate('2025-13-01'),null);assert.notEqual(api.strictDate('2024-02-29'),null);});
test('partial month remains a bounded interval, including leap day',()=>{const d=api.dateInterval('2024-02');assert.equal(d.end-d.start,28);assert.equal(d.precision,'month');});
test('year date retains year precision',()=>{const d=api.dateInterval('2025');assert.equal(d.end-d.start,364);assert.equal(d.precision,'year');});
test('no phenology gives no invented offset',()=>{assert.equal(api.clockRecord(sample(),null).status,'NO_PHENOLOGY');});
test('weekly peak preserves width and date difference sign',()=>{const r=api.clockRecord(sample(),phen());assert.equal(r.status,'AVAILABLE');assert.equal(r.lower,-11);assert.equal(r.upper,-5);assert.equal(r.anchor.end-r.anchor.start,6);});
test('month precision is propagated into offset interval',()=>{const s=sample();s.collection_date='2025-10';const r=api.clockRecord(s,phen());assert.equal(r.upper-r.lower,36);});
test('invalid collection date remains unavailable',()=>{const s=sample();s.collection_date='2025-02-30';assert.equal(api.clockRecord(s,phen()).status,'NO_COLLECTION_DATE');});
test('scope does not silently convert a host alias or state code',()=>{const s=sample();s.host='WGA';assert.equal(api.clockRecord(s,phen()).status,'NO_MATCHING_PROFILE');s.host=sample().host;s.state='ER';assert.equal(api.clockRecord(s,phen()).status,'NO_MATCHING_PROFILE');});
test('ambiguous overlapping profiles are not picked arbitrarily',()=>{const p=copy(fixture.ecological_clock);const extra=copy(p.profiles[0]);extra.profile_id='other';p.profiles.push(extra);assert.equal(api.clockRecord(sample(),api.validatePhenology(p)).status,'AMBIGUOUS_PROFILE');});
test('flat profile has no inferred peak',()=>{const p=copy(fixture.ecological_clock);p.profiles[0].bins.forEach(b=>b.value=1);assert.equal(api.clockRecord(sample(),api.validatePhenology(p)).status,'FLAT_PROFILE');});
test('zero seasonal profile has no positive anchor',()=>{const p=copy(fixture.ecological_clock);p.profiles[0].bins.forEach(b=>b.value=0);assert.equal(api.clockRecord(sample(),api.validatePhenology(p)).status,'NO_POSITIVE_VALUES');});
test('disconnected equally high peaks remain ambiguous',()=>{const p=copy(fixture.ecological_clock);p.profiles[0].bins[0].value=25;assert.equal(api.clockRecord(sample(),api.validatePhenology(p)).status,'AMBIGUOUS_PEAK');});
test('missing bins remain null and are not imputed',()=>{const p=phen();assert.equal(p.profiles[1].bins[2].value,null);});
test('negative profile values fail validation',()=>{const p=copy(fixture.ecological_clock);p.profiles[0].bins[0].value=-1;assert.throws(()=>api.validatePhenology(p),/nonnegative/);});
test('overlapping temporal bins fail validation',()=>{const p=copy(fixture.ecological_clock);p.profiles[0].bins[1].start=p.profiles[0].bins[0].start;assert.throws(()=>api.validatePhenology(p),/nonoverlapping/);});
test('provenance and synthetic status must be explicit',()=>{const p=copy(fixture.ecological_clock);delete p.synthetic;assert.throws(()=>api.validatePhenology(p),/synthetic/);p.synthetic=false;delete p.profiles[0].provenance.citation;assert.throws(()=>api.validatePhenology(p),/citation/);});
test('reviewed anchor is honored without inventing confidence',()=>{const p=copy(fixture.ecological_clock);p.profiles[0].anchor={earliest:'2025-10-10',latest:'2025-10-12',label:'Reviewed seasonal anchor',basis:'Supplied by fixture author'};const r=api.clockRecord(sample(),api.validatePhenology(p));assert.equal(r.lower,-4);assert.equal(r.upper,-2);assert.equal(r.anchor.method,'supplied');});
test('legacy report without references or ecology is supported',()=>{const d=copy(fixture);delete d.ecological_clock;delete d.public_reference_context;assert.equal(api.model(d).references.length,0);});
