#!/usr/bin/env python3
"""Finalize WINGS contextual phylogenies for Surveillance Explorer display.

This stage copies completed IQ-TREE trees into the Explorer naming convention,
builds the public-reference manifest from the contextual tip manifest, records
provenance/checksums, and writes a YAML config snippet.

Public accessions are preserved exactly as supplied. Accession versions are not
invented. Cross-segment reference linkage uses the explicit algorithmic grouping
already established upstream from exact concordance of isolate, collection date,
country, state, and host; provenance records that this is metadata-based grouping,
not independent BioSample verification.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import shutil
from collections import Counter, defaultdict
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Set

SEGMENTS = ("HA", "NA", "PB2", "PB1", "PA", "NP", "MP", "NS")
MANIFEST_FIELDS = (
    "reference_id",
    "segment",
    "tip_label",
    "accession_version",
    "isolate",
    "host",
    "collection_date",
    "country",
    "state",
    "linkage_basis",
)


def clean(value: object) -> str:
    return "" if value is None else str(value).strip()


def read_tsv(path: Path) -> List[dict]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        return [dict(row) for row in reader]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def validate_date(value: str) -> str:
    try:
        parsed = date.fromisoformat(value)
    except ValueError as exc:
        raise ValueError("--retrieved-on must be a full ISO date YYYY-MM-DD") from exc
    if parsed.isoformat() != value:
        raise ValueError("--retrieved-on must be a full ISO date YYYY-MM-DD")
    return value


def newick_leaf_names(text: str) -> Set[str]:
    """Extract leaf labels from IQ-TREE Newick output.

    WINGS/IQ-TREE labels generated by this pipeline contain no Newick delimiters.
    Quoted labels are unescaped conservatively for validation.
    """
    names: Set[str] = set()
    for match in re.finditer(r"(?:^|[,(])\s*([^():,;]+?)\s*(?=:)", text):
        label = match.group(1).strip()
        if label.startswith("'") and label.endswith("'") and len(label) >= 2:
            label = label[1:-1].replace("''", "'")
        if label:
            names.add(label)
    return names


def group_linkage_basis(rows: Iterable[dict]) -> Dict[str, str]:
    grouped: Dict[str, List[dict]] = defaultdict(list)
    for row in rows:
        reference_id = clean(row.get("reference_id")) or clean(row.get("accession"))
        grouped[reference_id].append(row)

    result: Dict[str, str] = {}
    for reference_id, group in grouped.items():
        if len(group) <= 1:
            result[reference_id] = ""
            continue

        # Upstream grouping used all five fields exactly. Re-check that invariant
        # here so the display manifest never silently claims stronger linkage.
        for field in ("isolate", "collection_date", "country", "state", "host"):
            values = {clean(row.get(field)).casefold() for row in group}
            if len(values) != 1:
                raise ValueError(
                    f"Public reference group {reference_id!r} has conflicting {field}; "
                    "cannot create cross-segment linkage"
                )
        segments = [clean(row.get("segment")).upper() for row in group]
        if len(segments) != len(set(segments)):
            raise ValueError(
                f"Public reference group {reference_id!r} has duplicate segment records"
            )
        result[reference_id] = (
            "algorithmic_exact_metadata_group:"
            "isolate+collection_date+country+state+host"
        )
    return result


def write_tsv(path: Path, rows: Iterable[dict], fields: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(fields), delimiter="\t", extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Finalize contextual trees, public-reference manifest, and provenance for WINGS Explorer."
    )
    parser.add_argument(
        "--context-dir",
        type=Path,
        default=Path("results/run_summary/contextual_phylogeny"),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/run_summary/public_references/contextual_display"),
    )
    parser.add_argument("--retrieved-on", required=True, type=validate_date)
    parser.add_argument(
        "--citation",
        default="NCBI Influenza Virus sequence and metadata export used for this WINGS analysis.",
    )
    args = parser.parse_args(argv)

    tip_manifest = args.context_dir / "contextual_tip_manifest.tsv"
    if not tip_manifest.is_file():
        raise FileNotFoundError(f"Missing contextual tip manifest: {tip_manifest}")

    all_rows = read_tsv(tip_manifest)
    public_rows = [row for row in all_rows if clean(row.get("tip_kind")) == "public_reference"]
    wings_rows = [row for row in all_rows if clean(row.get("tip_kind")) == "wings_sample"]
    if not public_rows:
        raise ValueError("Contextual tip manifest contains no public-reference rows")

    linkage = group_linkage_basis(public_rows)

    trees_dir = args.output_dir / "trees"
    trees_dir.mkdir(parents=True, exist_ok=True)
    tree_hashes: Dict[str, str] = {}
    segment_counts: Dict[str, dict] = {}

    for segment in SEGMENTS:
        source_tree = args.context_dir / f"{segment}.contextual.treefile"
        if not source_tree.is_file() or source_tree.stat().st_size == 0:
            raise FileNotFoundError(f"Missing or empty IQ-TREE treefile: {source_tree}")
        destination = trees_dir / f"{segment}_Tree.newick"
        shutil.copyfile(source_tree, destination)
        tree_hashes[segment] = sha256_file(destination)

        leaves = newick_leaf_names(destination.read_text(encoding="utf-8", errors="replace"))
        expected_public = {
            clean(row.get("tip_label"))
            for row in public_rows
            if clean(row.get("segment")).upper() == segment
        }
        expected_wings = {
            clean(row.get("tip_label"))
            for row in wings_rows
            if clean(row.get("segment")).upper() == segment
        }
        missing_public = sorted(expected_public - leaves)
        missing_wings = sorted(expected_wings - leaves)
        if missing_public or missing_wings:
            raise ValueError(
                f"Tree-tip validation failed for {segment}: "
                f"missing_public={len(missing_public)}, missing_wings={len(missing_wings)}"
            )
        segment_counts[segment] = {
            "tree_tips": len(leaves),
            "public_tips": len(expected_public),
            "wings_tips": len(expected_wings),
        }

    manifest_rows: List[dict] = []
    seen_accessions: Set[str] = set()
    seen_segment_tips: Set[tuple] = set()
    for source in public_rows:
        segment = clean(source.get("segment")).upper()  # NA is literal here.
        accession = clean(source.get("accession"))
        tip = clean(source.get("tip_label")) or accession
        reference_id = clean(source.get("reference_id")) or accession
        if segment not in SEGMENTS or not accession or not tip:
            raise ValueError(
                f"Invalid contextual public tip: segment={segment!r}, accession={accession!r}, tip={tip!r}"
            )
        if accession in seen_accessions:
            raise ValueError(f"Duplicate public accession across manifest: {accession}")
        key = (segment, tip)
        if key in seen_segment_tips:
            raise ValueError(f"Duplicate segment/tip pair: {segment}/{tip}")
        seen_accessions.add(accession)
        seen_segment_tips.add(key)
        manifest_rows.append(
            {
                "reference_id": reference_id,
                "segment": segment,
                "tip_label": tip,
                # Kept in the legacy field name for backward compatibility.
                # The importer patch accepts either accession or accession.version.
                "accession_version": accession,
                "isolate": clean(source.get("isolate")),
                "host": clean(source.get("host")),
                "collection_date": clean(source.get("collection_date")),
                "country": clean(source.get("country")),
                "state": clean(source.get("state")),
                "linkage_basis": linkage.get(reference_id, ""),
            }
        )

    manifest_path = args.output_dir / "manifest.tsv"
    write_tsv(manifest_path, manifest_rows, MANIFEST_FIELDS)
    manifest_hash = sha256_file(manifest_path)

    reason_counts = Counter(clean(row.get("selection_reason")) for row in public_rows)
    genotype_counts = Counter(clean(row.get("genotype")) for row in public_rows)
    provenance = {
        "schema_version": 2,
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "manifest_sha256": manifest_hash,
        "retrieved_on": args.retrieved_on,
        "selection_notes": (
            "Automated WINGS contextual-reference selection from the prepared North American avian H5Nx pool. "
            "Each segment uses 160 same-whole-genome-genotype references, 60 same-GenoFLU-segment-type "
            "references, and 30 other assigned avian background references when available. WINGS study "
            "segments require overall_status=PASS. Cross-segment public reference_id grouping is based on "
            "exact concordance of isolate, collection_date, country, state, and host and is algorithmic metadata "
            "grouping rather than independent BioSample verification."
        ),
        "citation": args.citation,
        "tree_sha256": tree_hashes,
        "source_tip_manifest": str(tip_manifest.resolve()),
        "record_count": len(manifest_rows),
        "reference_group_count": len({row["reference_id"] for row in manifest_rows}),
        "selection_reason_counts": dict(sorted(reason_counts.items())),
        "genotype_counts_by_segment_record": dict(sorted(genotype_counts.items())),
        "segment_counts": segment_counts,
        "accession_policy": (
            "Public GenBank accessions are preserved exactly as supplied by the NCBI export; accession versions "
            "are not fabricated when absent."
        ),
    }
    provenance_path = args.output_dir / "provenance.json"
    provenance_path.write_text(json.dumps(provenance, indent=2) + "\n", encoding="utf-8")

    config_snippet = args.output_dir / "public_references.config.yaml"
    config_snippet.write_text(
        "public_references:\n"
        "  enabled: true\n"
        f"  manifest: {manifest_path.as_posix()}\n"
        f"  provenance: {provenance_path.as_posix()}\n"
        f"  tree_dir: {trees_dir.as_posix()}\n"
        '  tree_pattern: "{segment}_Tree.newick"\n',
        encoding="utf-8",
    )

    summary = {
        "manifest": str(manifest_path),
        "provenance": str(provenance_path),
        "trees": str(trees_dir),
        "config_snippet": str(config_snippet),
        "public_records": len(manifest_rows),
        "reference_groups": len({row["reference_id"] for row in manifest_rows}),
        "segment_counts": segment_counts,
    }
    (args.output_dir / "finalize_summary.json").write_text(
        json.dumps(summary, indent=2) + "\n", encoding="utf-8"
    )

    print("Finalized contextual public-reference display inputs:")
    for segment in SEGMENTS:
        counts = segment_counts[segment]
        print(
            f"  {segment}: {counts['wings_tips']} WINGS + "
            f"{counts['public_tips']} public = {counts['tree_tips']} tree tips"
        )
    print(f"Manifest: {manifest_path}")
    print(f"Provenance: {provenance_path}")
    print(f"Trees: {trees_dir}")
    print(f"Config snippet: {config_snippet}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
